name: Check and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always
  DONT_SAVE_RESULT: 1
  RAYON_NUM_THREADS: 4

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Check compilation for no_std
        run: |
          cargo build --no-default-features --features=no_std

      - name: Run single-thread tests
        run: |
          cargo check
          cargo test

      - name: Run multi-thread tests
        run: |
          cargo check --features rayon
          cargo test --features rayon

  run_tests_for_wasm:
    name: Test wasm32 on ubuntu-latest
    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_TARGET: "wasm32-wasip2"
      CARGO_TARGET_WASM32_WASIP2_RUNNER: "wasmtime --dir=. --"

    steps:
      - uses: actions/checkout@v6

      - name: Setup `wasmtime`
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "40.0.0"

      - name: Install Rust toolchain and target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip2
          cache-on-failure: "true"
          rustflags: ""

      - name: Check compilation for no_std
        run: |
          cargo build --no-default-features --features=no_std

      - name: Run tests
        run: |
          cargo check
          cargo test

  doc:
    name: Test documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain and target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          cache-on-failure: "true"
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs
