name: Check and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always
  DONT_SAVE_RESULT: 1
  RAYON_NUM_THREADS: 4
  CARGO_TARGET_WASM32_WASIP2_RUNNER: "wasmtime --dir=. --"

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Check compilation for no_std
        run: |
          cargo build --no-default-features --features=no_std

      - name: Run single-thread tests
        run: |
          cargo check
          cargo test

      - name: Run multi-thread tests
        run: |
          cargo check --features rayon
          cargo test --features rayon

      - name: Setup `wasmtime`
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        # Use the action provided by the Bytecode Alliance
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "40.0"

      - name: Check compilation for no_std + WASI
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        run: |
          cargo build --target=wasm32-wasip2 --no-default-features --features=no_std

      - name: Run tests for WASI
        if: "${{ matrix.os == 'ubuntu-latest' }}"
        run: |
          cargo check --target=wasm32-wasip2
          cargo test --target=wasm32-wasip2
